# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.1.1 on 2026-09-13 12:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternalApiKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(max_length=32, unique=True)),
                ("key", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Audit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("domain", models.CharField(db_index=True, max_length=253)),
                ("url", models.URLField(max_length=2048)),
                ("channel_idx", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("partially_completed", "Partially completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("requested_by", models.CharField(max_length=200)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "indexes": [models.Index(fields=["domain", "status"], name="siteintel_audit_domain_status")],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("processed", models.JSONField(blank=True, default=dict)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("duration_s", models.FloatField(blank=True, null=True)),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ssrf", "Refused by the SSRF guard"),
                            ("timeout", "Timed out"),
                            ("upstream", "Upstream error"),
                            ("truncated", "Body over the byte cap"),
                            ("invalid", "Invalid or oversized payload"),
                            ("recording_missing", "No recording for the domain"),
                        ],
                        max_length=32,
                    ),
                ),
                ("error_detail", models.TextField(blank=True)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reports", to="django_siteintel.audit"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("audit", "source"), name="siteintel_report_audit_source")
                ],
            },
        ),
    ]
