# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.1.1 on 2026-09-13 14:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_siteintel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="run_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="report",
            name="error_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ssrf", "Refused by the SSRF guard"),
                    ("timeout", "Timed out"),
                    ("upstream", "Upstream error"),
                    ("truncated", "Body over the byte cap"),
                    ("invalid", "Invalid or oversized payload"),
                    ("recording_missing", "No recording for the domain"),
                    ("internal", "Unexpected error"),
                ],
                max_length=32,
            ),
        ),
    ]
